title: Mars College
markdown: kramdown
email: gene@genekogan.com
description: >- 
  Mars College is an educational program, R&D lab, and intentional community dedicated to cultivating a low-cost, high-tech lifestyle.
baseurl: "" 
url: "mars.college"
twitter_username: genekogan
github_username:  mars-college

collections:
  pages:
    output: true
    permalink: /:path/
  gallery:
    output: true
    permalink: /gallery/:path/

sass:
  sass_dir: _scss
  style: :compressed
  
plugins:
  - jekyll-feed

exclude:
  - scripts/
